### ISSUE TITLE
Addon keeps resetting settings.

### ISSUE THREAD

**Issue by Warpavp2** [casualshammy/NameplateCooldowns#85] opened 2021-07-18 01:58 UTC
**Describe the bug**
When disabling spells they all reset back on after closing the window for spell selection.

**To Reproduce**
1. Go to '...' Open NamePlateCooldowns Window
2. Click on '....' Turn on or off some spells.
3. Scroll down to '....' Close window and reopen a few times. Or do an arena idk.
4. See error Everything goes back to ON.

**Expected behavior**
The spells should stay off if you have them off.
**Screenshots**

**Comment by ART515** [comment] 2021-07-31 03:14
The same problem occurs to me as well.

**Comment by ART515** [comment] 2021-07-31 21:29
Do we have any update? :) 
I hope it's gonna be fixed, I would like to use the addon, it's amazing :) but now I can't till the settings are keeping reseting.

If I can help anything let me know.

**Comment by casualshammy** [comment] 2021-07-31 21:40
Hello.
I cannot reproduce this bug currently. I have opened the list of spells and then tried to enable/disable some spells. Their state was saved without any issue. Maybe I'm doing something wrong? Are you closing WoW client correctly? Addon settings are not saved if WoW client is crashed or closed, by example, by Alt-F4.

**Comment by ART515** [comment] 2021-08-01 00:45
I don't have to close the WoW Client to reproduce the issue.

To be honest, I'm not sure when the issue is reproduced 100%, but that's what I've done:

1. Installed the addon (via CurseForge)
2. Opened the UI of it.
3. Opened the spells section
4. Double clicked the "Disable all" -> worked fine
5. Then I just configured all the spells for all the classes one by one. (enabled some spells for each classes) - here what was interesting that some spells appeared multiple times.
6. Then I left the Spells section, or by closing the Addon interface or by navigating to another tab on the addon's UI. 
7. When I moved back to the spells section sometimes everything was fine (as I configured it) sometimes the settings was resetting.

As I observed it was also enough if I pressed the Test Mode again and again while I was into the spells tab and the settings has been resetted.

I'm not sure if any of the above interaction forces the addon to reset the configs or it just resets it periodically (1-2m). 

Totally I've tried to configure all the required spells 4 times (for all the classes) and all the configs has been reseted all of the times.

I truly hope that I succeeded to help. (I'm not the best QA while I'm also a developer :) )

**Comment by ART515** [comment] 2021-08-01 00:47
In case we could make a meeting to test it, I could share my screen in order to figure out where is the problem.

**Comment by ART515** [comment] 2021-08-01 01:00
Uploading nameplatecooldowns_config_ressetting_bug.mp4…

**Comment by ART515** [comment] 2021-08-01 01:03
https://user-images.githubusercontent.com/28508280/127755860-dccb395a-4b56-419c-bb9b-1b6a1a38e8bd.mp4

I've created a video about the bug. It's compressed, that's why it's so blurry. But I think you will be able to figure out what was happened exactly. (maybe the concretely selected spells matters?)

The video was made exactly after I've clearly reinstalled the addon.

**Comment by ART515** [comment] 2021-08-01 01:16
I've also found out that if I do not use the disable all feature but I manually disable all the spells the settings are not reseted. (or until now they were not reseted) BUT some of the spells constantly becomes active even if I disable them, like the mage's counterspell the DK's stunn. (this happened when I pressed the test mode button)

**Comment by casualshammy** [comment] 2021-08-01 14:42
Ah, I guess you've found a very old 'bug' I was too lazy to fix. If test mode is enabled, all changes in spells will be lost after disabling test mode. I think I'll just disable the ability to edit spells while test mode is active.

**Comment by ART515** [comment] 2021-08-01 20:00
are u going to fix it (somehow) ?

**Comment by casualshammy** [comment] 2021-08-01 21:03
> I think I'll just disable the ability to edit spells while test mode is active.

**Comment by casualshammy** [comment] 2021-08-02 18:40
I hope this problem is fixed in the latest release (90100.4-release)

**Closed as completed** 2021-09-09 06:47 UTC
Labels: type: bug, status: fixed
