### ISSUE TITLE
After restart ALL spells are activated again

### ISSUE THREAD

**Issue by Rackelhardt** [casualshammy/NameplateCooldowns#68] opened 2021-02-22 19:12 UTC
I just activated a few spells like Trinket, Interrupts and some key-spells like Devine Shield or Convoke the Spirits.
I deactivated the other spells.

When i log out (and yes, i do the save logout not Alt+F4 or something) and restart the game ALL spells are active again.
Other options i changed were saved. Its just the spells.

/e: ok weird... i figgured out that when i let the game menu open in the background and press "ok" and "back to game" after i change the settings in your addon and THEN close the addon it saves the spells.
But when i close Blizzard game menu in background before i do the changes it wont save it.

But maybe its just coincidence.
At least it works now....

**Comment by casualshammy** [comment] 2021-02-24 15:04
Can't reproduce this bug. If I've understood you clearly, the problem happens when you open game menu, then close it, then make changes in addon, then open game menu again and logout, right? But (if there isn't some weird Blizzard bug) addons don't care about game menu at all. Also NameplateCooldowns' options are applied immediately, there is no need to close options window or something like that.

**Closed** 2021-03-21 15:06 UTC
Labels: status:wontfix, type:bug
